### ISSUE TITLE
Undesired access denieds due to incorrect dependency chain on role assignment

### ISSUE THREAD

**Issue by cveld** [CloudNationHQ/terraform-azure-kv#15]
Using version 0.4.0.

Currently the keyvault id is already consumed by subsequent resources whereas the admin access role assignment is still being created. This results in access denied errors.

Desired is a dependency from the output towards the role assignment. Optionally also using a `time_sleep`.

E.g. (code taken from other context)
```hcl
resource "time_sleep" "wait_for_key_vault" {
  depends_on      = [azurerm_role_assignment.shared_key_vault_administrator]
  create_duration = "10s"
}

output "key_vault" {
  depends_on = [time_sleep.wait_for_key_vault]
  value      = azurerm_key_vault.kv
}
```

**Comment by eddy-vera** [comment]
See https://github.com/CloudNationHQ/terraform-azure-kv/issues/35, this happens when existing secrets are used which are non-randomly generated but you might want to store in a KV module.
