### ISSUE TITLE
[BUG] - Random provider error

### ISSUE THREAD

**Issue by cndaan** [CloudNationHQ/terraform-azure-kv#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Module Version

0.12.0

### Terraform Version

latest

### AzureRM Provider Version

">= 3.0.2, ~> 3.61, ~> 3.95, < 4.0.0"

### Short Description

Failed to query available provider packages on random provider

### Terraform Configuration Files

module "kv" {
  source  = "cloudnationhq/kv/azure"
  version = "~> 0.12.0"

  vault = {
    name          = module.naming.key_vault.name_unique
    location      = module.rg.groups.kv.location
    resourcegroup = module.rg.groups.kv.name
  }
}

### Expected Behaviour

initializing the random provider

### Actual Behaviour

```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/random: no available releases match the given constraints ~> 3.0,
│ >= 3.3.2, ~> 3.5.1, ~> 3.6
```

**Comment by dkooll** [comment]
solved in #50 by @eddy-vera
